# Generated by Django 2.0.7 on 2022-05-28 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('visa_status', models.CharField(max_length=50)),
                ('salary_expect', models.CharField(max_length=50, null=True)),
                ('ph_number', models.CharField(max_length=50, null=True)),
                ('employment_status', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('work_experience', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='formentry',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preliminary_form.Resume'),
        ),
    ]
