# Generated by Django 2.0.7 on 2022-05-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preliminary_form', '0003_auto_20220528_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='education',
            new_name='file_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='resume',
            name='file_data_in_bytes',
            field=models.BinaryField(null=True),
        ),
    ]
